# Generated by Django 5.2 on 2025-05-31 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_alter_student_level'),
        ('school_app', '0002_remove_post_image_post_is_image_alter_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='picture',
            field=models.ImageField(upload_to='lecturers/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_level', to='school_app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
