# Generated by Django 5.2 on 2025-06-18 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=400)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('EPUB', 'EPUB')], max_length=50)),
                ('download_link', models.URLField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('NOVEL', 'Novel'), ('SCIENCE_BOOK', 'Science Book'), ('HISTORY', 'History'), ('MAGAZINES', 'Magazine')], max_length=50)),
                ('edition', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(max_length=25, null=True)),
                ('summary', models.TextField(blank=True, max_length=500000)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('is_due', models.DateTimeField()),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('Borrow', 'Borrow'), ('Return', 'Return')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.ebook')),
                ('physical_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.physicalbook')),
            ],
            options={
                'verbose_name': 'Book Record',
                'verbose_name_plural': 'Book Records',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
