# Generated by Django 5.2 on 2025-06-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrecord',
            old_name='due_date',
            new_name='is_due',
        ),
    ]
