# Generated by Django 5.2 on 2025-06-02 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_rename_due_date_bookrecord_is_due'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrecord',
            old_name='Physical_book',
            new_name='physical_book',
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='transaction_type',
            field=models.CharField(choices=[('Borrow', 'Borrow'), ('Return', 'Return')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file_format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EPUB', 'EPUB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='physicalbook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physicalbook',
            name='edition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='physicalbook',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='physicalbook',
            name='type',
            field=models.CharField(choices=[('NOVEL', 'Novel'), ('SCIENCE_BOOK', 'Science Book'), ('HISTORY', 'History'), ('MAGAZINES', 'Magazine')], max_length=50),
        ),
    ]
