# Generated by Django 5.2 on 2025-06-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_rename_physical_book_bookrecord_physical_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalbook',
            name='edition',
            field=models.CharField(),
        ),
    ]
