# Generated by Django 5.2 on 2025-06-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_physicalbook_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalbook',
            name='author',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='physicalbook',
            name='edition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
