# Generated by Django 5.2 on 2025-05-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='is_image',
            field=models.ImageField(null=True, upload_to='others/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400')]),
        ),
        migrations.AlterField(
            model_name='identitycard',
            name='picture',
            field=models.ImageField(upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_image',
            field=models.ImageField(blank=True, null=True, upload_to='exams/'),
        ),
    ]
