# Generated by Django 5.2 on 2025-06-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='event_type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Holiday', 'Holiday'), ('Sport', 'Sport'), ('Cultural', 'Cultural'), ('Deadline', 'Deadline')], default='Academic', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Not Paid', 'Not Paid')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=100),
        ),
    ]
