# Generated by Django 5.2 on 2025-05-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_alter_exam_academic_session_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='end_time',
        ),
    ]
