# Generated by Django 5.2 on 2025-05-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_remove_lecture_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Department',
            new_name='department',
        ),
    ]
