# Generated by Django 5.2 on 2025-05-25 22:00

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_rename_department_exam_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['event_date', 'start_time']},
        ),
        migrations.AddField(
            model_name='calendar',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calendar',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='event_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calendar',
            name='event_type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Holiday', 'Holiday'), ('Sport', 'Sport'), ('Cultural', 'Cultural'), ('Deadline', 'Deadline')], default='Academic'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'Lecturer'}, related_name='teach_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Test', 'Test'), ('Main Exam', 'Main Exam')], default='Main Exam', max_length=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.academicsession'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.course'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecturer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Lecturer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='venue',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='timetable',
            name='week_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(upload_to='media/lecturers')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'Lecturer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
